


- name: Set variable for /opt/awx/its-plugins directory
  stat:
    path: "/opt/awx/its-plugins"
  register: opt_awx_its_plugins_dir_check

- name: Create the /opt/awx/its-plugins directory if it is not present
  ansible.builtin.file:
    path: "/opt/awx/its-plugins/"
    state: directory
    mode: '0755'
    recurse: yes
  when: not opt_awx_its_plugins_dir_check.stat.exists == true
  
- name: Copy Over ansible-awx-dynamic-inventories Directory To /opt/awx/its-plugins/
  ansible.builtin.copy:
    src: "{{ role_path }}/files/ansible-awx-dynamic-inventories.tar.gz"
    dest: "/opt/awx/its-plugins/"
  

- name: Unarchive ansible-awx-dynamic-inventories.tar.gz
  ansible.builtin.shell: tar -xvf ansible-awx-dynamic-inventories.tar.gz
  args:
    executable: /bin/bash
    chdir: /opt/awx/its-plugins/


- name: Delete ansible-awx-dynamic-inventories Tar File
  ansible.builtin.shell: rm -rf ansible-awx-dynamic-inventories.tar.gz
  args:
    executable: /bin/bash
    chdir: /opt/awx/its-plugins/
    
       
- name: Create Required AD Dynamic Directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0775
  loop:
    - /opt/awx/inventories/AWX-Nodes
    - /opt/awx/inventories/CAS-Nodes
    - /opt/awx/inventories/IAM-Test-Dev


- name: Copy Over IAM-Test-Dev-ldap-ad.ini File To /opt/awx/inventories/IAM-Test-Dev/
  ansible.builtin.copy:
    src: "{{ role_path }}/files/IAM-Test-Dev-ldap-ad.ini"
    dest: "/opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini"

- name: Copy Over CAS-Nodes-ldap-ad.ini File To /opt/awx/inventories/CAS-Nodes/
  ansible.builtin.copy:
    src: "{{ role_path }}/files/CAS-Nodes-ldap-ad.ini"
    dest: "/opt/awx/inventories/CAS-Nodes/ldap-ad.ini"
    

- name: Copy Over AWX-Nodes-ldap-ad.ini File To /opt/awx/inventories/AWX-Nodes/
  ansible.builtin.copy:
    src: "{{ role_path }}/files/AWX-Nodes-ldap-ad.ini"
    dest: "/opt/awx/inventories/AWX-Nodes/ldap-ad.ini"
 
 
 

##### Entering AD Credentials Into IAM-Test-Dev-ldap-ad.ini File
- name: Entering ad_username Into /opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini"
    regexp: 'ad_username'
    replace: "{{ ad_username }}"

- name: Entering ad_password Into /opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini"
    regexp: 'ad_password'
    replace: "{{ ad_password }}"

- name: Entering node_cert_path Into /opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/IAM-Test-Dev/ldap-ad.ini"
    regexp: 'node_cert_path'
    replace: "/etc/letsencrypt/archive/{{ ansible_nodename }}/cert1.pem"



##### Entering AD Credentials Into CAS-Nodes-ldap-ad.ini File
- name: Entering ad_username Into /opt/awx/inventories/CAS-Nodes/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/CAS-Nodes/ldap-ad.ini"
    regexp: 'ad_username'
    replace: "{{ ad_username }}"

- name: Entering ad_password Into /opt/awx/inventories/CAS-Nodes/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/CAS-Nodes/ldap-ad.ini"
    regexp: 'ad_password'
    replace: "{{ ad_password }}"

- name: Entering node_cert_path Into /opt/awx/inventories/CAS-Nodes/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/CAS-Nodes/ldap-ad.ini"
    regexp: 'node_cert_path'
    replace: "/etc/letsencrypt/archive/{{ ansible_nodename }}/cert1.pem"


##### Entering AD Credentials Into AWX-Nodes-ldap-ad.ini File
- name: Entering ad_username Into /opt/awx/inventories/AWX-Nodes/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/AWX-Nodes/ldap-ad.ini"
    regexp: 'ad_username'
    replace: "{{ ad_username }}"

- name: Entering ad_password Into /opt/awx/inventories/AWX-Nodes/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/AWX-Nodes/ldap-ad.ini"
    regexp: 'ad_password'
    replace: "{{ ad_password }}"

- name: Entering node_cert_path Into /opt/awx/inventories/AWX-Nodes/ldap-ad.ini File
  replace:
    path: "/opt/awx/inventories/AWX-Nodes/ldap-ad.ini"
    regexp: 'node_cert_path'
    replace: "/etc/letsencrypt/archive/{{ ansible_nodename }}/cert1.pem"



##### Entering AD Credentials Into custom_add_hosts_to_a_inventory.py File
- name: Entering ad_username Into custom_add_hosts_to_a_inventory.py File
  replace:
    path: "/opt/awx/its-plugins/ansible-awx-dynamic-inventories/api/cronjob/custom_add_hosts_to_a_inventory.py"
    regexp: 'awx-admin-user'
    replace: "{{ ad_username }}"

- name: Entering ad_password Into custom_add_hosts_to_a_inventory File
  replace:
    path: "/opt/awx/its-plugins/ansible-awx-dynamic-inventories/api/cronjob/custom_add_hosts_to_a_inventory.py"
    regexp: 'password'
    replace: "{{ ad_password }}"



- name: Entering ansible_nodename Into custom_add_hosts_to_a_inventory File
  replace:
    path: "/opt/awx/its-plugins/ansible-awx-dynamic-inventories/api/cronjob/custom_add_hosts_to_a_inventory.py"
    regexp: 'awx-server-hostname'
    replace: "{{ ansible_nodename }}"



- name: Creates a Cronjob like "*/5 * * * ..... /dev/null"
  ansible.builtin.cron:
    name: "Run Python LDAP Plugin"
    minute: "*/5"
    hour: "*"
    job: 'python3 /opt/awx/its-plugins/ansible-awx-dynamic-inventories/api/cronjob/custom_add_hosts_to_a_inventory.py --inventory "2" --source "/opt/awx/inventories/IAM-Test-Dev/"  >/dev/null 2>&1'