- name: Reinstall k3s
  ansible.builtin.shell: curl -sfL https://get.k3s.io | sudo bash -            
  args:
    executable: /bin/bash

- name: Fix k3s Permissions
  ansible.builtin.shell: chmod 644 /etc/rancher/k3s/k3s.yaml           
  args:
    executable: /bin/bash  

- name: Fix k3s Directory Permissions
  ansible.builtin.shell: "cp /etc/rancher/k3s/k3s.yaml ~/.kube/config  &&  chown $USER ~/.kube/config"
  args:
    executable: /bin/bash  


- name: Create /admin_tools/helm Directory
  ansible.builtin.file:
    path: /admin_tools/helm
    state: directory


- name: Create /admin_tools/certs Directory
  ansible.builtin.file:
    path: /admin_tools/certs
    state: directory

- name: Install Packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: latest
  loop:
    - nginx
    - wget
    - tar
    - jq



- name: Download Helm Binary
  ansible.builtin.shell: wget https://get.helm.sh/helm-v3.15.3-linux-amd64.tar.gz && tar -xvf helm-v3.15.3-linux-amd64.tar.gz 
  args:
    executable: /bin/bash
    chdir: /admin_tools/helm


- name: Copy Helm Binary Over to /usr/bin
  ansible.builtin.shell: cp -r linux-amd64/helm /usr/bin
  args:
    executable: /bin/bash
    chdir: /admin_tools/helm

- name: Remove file /var/lib/rancher/k3s/server/manifests/traefik.yaml
  ansible.builtin.file: 
    path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
    state: absent 

- name: Uninstall Traefik Using Helm
  ansible.builtin.shell: helm uninstall traefik traefik-crd -n kube-system
  args:
    executable: /bin/bash

- name: Restart K3s service
  ansible.builtin.systemd:
    name: k3s
    state: restarted



- name: Copy Self Generate SSL Cert To /etc/nginx/certs directory
  ansible.builtin.shell: cp -r /admin_tools/awx-operator/awx-deploy/tls.crt  /etc/nginx/certs/server.crt
  args:
    executable: /bin/bash


- name: Copy Self Generate SSL Private Key To /etc/nginx/certs directory
  ansible.builtin.shell: cp -r /admin_tools/awx-operator/awx-deploy/tls.key  /etc/nginx/certs/server.key
  args:
    executable: /bin/bash




- name: Get AWX service details
  ansible.builtin.shell: kubectl get service -n awx
  args:
    executable: /bin/bash
  register: awx_service_output



- name: Extract last line from service output
  set_fact:
    last_line: "{{ awx_service_output.stdout_lines | last }}"

- name: Set awx_service_output port variable
  set_fact:
    awx_service_output: "{{ last_line | regex_replace('[^0-9]', '') }}"


- name: Copy Over Custom Nginx config_files to /etc/nginx/conf.d/awx-ssl.conf
  ansible.builtin.template:
    src: "{{ role_path }}/files/awx-ssl.conf"
    dest: "/etc/nginx/conf.d/awx-ssl.conf"


- name: Copy Over Custom Nginx config_files to /etc/nginx/conf.d/awx-no-ssl.conf
  ansible.builtin.copy:
    src: "{{ role_path }}/files/awx-no-ssl.conf"
    dest: "/etc/nginx/conf.d/awx-no-ssl.conf"




- name: Restart Nginx
  service:
    name: nginx
    state: restarted





  

#- name: Copy Over Custom awx-deploy to /admin_tools/awx-operator
#  ansible.builtin.copy:
#    src: "/admin_tools/awx-deploy"
#    dest: "/admin_tools/awx-operator"
#    remote_src: yes 


